### ISSUE TITLE
[Chat] При написании сообщений в чат пишется дополнительный текст

### ISSUE THREAD

**Issue by Jucepine** [Macsimka/BugTracker#1]
Скр.: http://i.imgur.com/0Fp4Qfv.png

09:34:26 [S] <1:Bukotest>: 1  (CHAT_MSG_SAY)
09:34:48 [S] [1:Bukotest]: 1  (CHAT_MSG_SAY)
09:35:01 [Y] [1:Bukotest]: 1  (CHAT_MSG_YELL)
09:38:28 [S] [1:Bukotest]: 123  (CHAT_MSG_SAY)

**Comment by Jucepine** [comment]
Скр.: http://i.imgur.com/oGSwmjh.png

09:46:58 Max is appearing to your location.  (CHAT_MSG_SYSTEM)
09:47:01 [4] [1:Bukotest]: првет  (CHAT_MSG_CHANNEL)
09:47:01 [4] [1:Bukotest]: првет  (CHAT_MSG_CHANNEL)

**Comment by Lordron** [comment]
Аддоны выключи, я без аддонов и все нормально.

**Comment by Jucepine** [comment]
да все уже, это не актуально, все нашлось
