### ISSUE TITLE
[Цепочка Крыльев Пустоты] В услужении у Иллидари - видео #1

### ISSUE THREAD

**Issue by Jucepine** [Macsimka/BugTracker#8]
http://ru.wowhead.com/quest=11013

Квест нельзя сдать, нпц не принимает:
![123](https://cloud.githubusercontent.com/assets/4539593/24799370/1dfd014e-1b9b-11e7-8c17-536b9bd8941b.png)

**Comment by Macsimka** [comment]
Теперь принимает.
http://i.imgur.com/ok62As3.jpg
